spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      sentinel:
        password: fpeltmWkd!@#123
        master: mymaster
        nodes:
          - redis.redis:26379
      password: fpeltmWkd!@#123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

kms:
  apiKey: ${KMS_API_KEY}
  url: ${KMS_URL}
  secretKey: ${KMS_SECRET_KEY}

openapi:
  koreaexim:
    enable: false
    key: MTTECKpBsABg74lVDXK6w0NxJrY6LE2p
    base-url: https://www.koreaexim.go.kr

  naver:
    enable: true
    key:
    base-url: https://m.stock.naver.com
    path:
      exchange: /front-api/marketIndex/exchange/new
      round: /front-api/marketIndex/productDetail?category=exchange&reutersCode=FX_USDKRW

logging:
  level:
    org.springframework.r2dbc: INFO
    kr.co.kwt.exchange: INFO
    io.r2dbc.pool: INFO
    org.hibernate.sql: INFO