spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:mysql://mysql-cluster.kwt-dev:6446/exchange
    username: root
    password: rootqlalfqjsgh486
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
      validation-depth: REMOTE  # 실제 DB 연결 확인
      max-create-connection-time: 2s
      max-acquire-time: 4s
      max-life-time: 2h        # 커넥션 최대 수명
      enable-metrics: true     # 모니터링을 위한 메트릭 활성화
    properties:
      connect-timeout: 3s
      ssl: false               # SSL 설정이 불필요한 경우

openapi:
  koreaexim:
    enable: false
    key: MTTECKpBsABg74lVDXK6w0NxJrY6LE2p
    base-url: https://www.koreaexim.go.kr

  naver:
    enable: true
    key:
    base-url: https://m.stock.naver.com/front-api/marketIndex/exchange/new

logging:
  level:
    org.springframework.r2dbc: INFO
    kr.co.kwt.exchange: DEBUG
    io.r2dbc.pool: INFO