spring:
  config:
    activate:
      on-profile: local

  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/resources/templates

  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQLDialect           # SSL 설정이 불필요한 경우
        default_batch_fetch_size: 100

kms:
  apiKey: c07139d0f57d841f1aa4589b0d4b653cf8fbbb57b3b7ac52d07776129e4e95ae
  url: https://kms.kwt.co.kr/api/secrets
  secretKey: exchange

openapi:
  koreaexim:
    enable: false
    key: MTTECKpBsABg74lVDXK6w0NxJrY6LE2p
    base-url: https://www.koreaexim.go.kr

  naver:
    enable: true
    key:
    base-url: https://m.stock.naver.com
    path:
      exchange: /front-api/marketIndex/exchange/new
      round: /front-api/marketIndex/productDetail?category=exchange&reutersCode=FX_USDKRW

logging:
  level:
    kr.co.kwt.exchange: DEBUG
    org.hibernate.sql: INFO

server:
  shutdown: immediate # 즉시 종료

service:
  id: "exchange"
  name: "환율계산기"
  url: http://localhost:8080
  themeColor: "#00ff88"