spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

kms:
  apiKey: bf3a6d5c2cdebbaf1585f23b2759e8897b6e4c83ffb8cd4ef0a7bd64a4ec97d6
  url: http://kms.kms/api/secrets
  secretKey: exchange

openapi:
  koreaexim:
    enable: false
    key: MTTECKpBsABg74lVDXK6w0NxJrY6LE2p
    base-url: https://www.koreaexim.go.kr

  naver:
    enable: true
    key:
    base-url: https://m.stock.naver.com
    path:
      exchange: /front-api/marketIndex/exchange/new
      round: /front-api/marketIndex/productDetail?category=exchange&reutersCode=FX_USDKRW

logging:
  level:
    org.springframework.r2dbc: INFO
    kr.co.kwt.exchange: INFO
    io.r2dbc.pool: INFO
    org.hibernate.sql: INFO