spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    pool:
      initial-size: 10
      max-size: 20
      max-idle-time: 30m
      validation-query: SELECT 1
      validation-depth: REMOTE  # 실제 DB 연결 확인
      max-create-connection-time: 2s
      max-acquire-time: 4s
      max-life-time: 2h        # 커넥션 최대 수명
      enable-metrics: true     # 모니터링을 위한 메트릭 활성화
    properties:
      connect-timeout: 3s
      ssl: false               # SSL 설정이 불필요한 경우

kms:
  apiKey: bf3a6d5c2cdebbaf1585f23b2759e8897b6e4c83ffb8cd4ef0a7bd64a4ec97d6
  url: http://kms.kms/api/secrets
  secretKey: exchange

openapi:
  koreaexim:
    enable: false
    key: MTTECKpBsABg74lVDXK6w0NxJrY6LE2p
    base-url: https://www.koreaexim.go.kr

  naver:
    enable: true
    key:
    base-url: https://m.stock.naver.com
    path:
      exchange-rate: /front-api/marketIndex/exchange/new
      degree-count: /front-api/marketIndex/productDetail?category=exchange&reutersCode=FX_USDKRW

logging:
  level:
    org.springframework.r2dbc: INFO
    kr.co.kwt.exchange: INFO
    io.r2dbc.pool: INFO