spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:mysql://mysql-cluster.kwt-prod:6446/exchange
    username: exchange_user
    password: exchange_password
    properties:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

exchange:
  api:
    key: MTTECKpBsABg74lVDXK6w0NxJrY6LE2p
    base-url: https://www.koreaexim.go.kr

logging:
  level:
    org.springframework.r2dbc: INFO
    kr.co.kwt.exchange: INFO
    io.r2dbc.pool: INFO