spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:mysql://mysql-router-service:3306/exchange
    username: root
    password: rootqlalfqjsgh486
    properties:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m
      validation-query: SELECT 1

exchange:
  api:
    key: MTTECKpBsABg74lVDXK6w0NxJrY6LE2p
    base-url: https://www.koreaexim.go.kr

logging:
  level:
    org.springframework.r2dbc: DEBUG
    kr.co.kwt.exchange: DEBUG
    io.r2dbc.pool: DEBUG