INSERT INTO country (id, currency_code, country_name, country_flag)
VALUES (1, 'USD', 'United States', '🇺🇸'),
       (2, 'EUR', 'Eurozone', '🇪🇺'),
       (3, 'JPY(100)', 'Japan', '🇯🇵'),
       (4, 'GBP', 'United Kingdom', '🇬🇧'),
       (5, 'AUD', 'Australia', '🇦🇺'),
       (6, 'CAD', 'Canada', '🇨🇦'),
       (7, 'CHF', 'Switzerland', '🇨🇭'),
       (8, 'CNY', 'China', '🇨🇳'),
       (9, 'HKD', 'Hong Kong', '🇭🇰'),
       (10, 'NZD', 'New Zealand', '🇳🇿'),
       (11, 'SEK', 'Sweden', '🇸🇪'),
       (12, 'KRW', 'Korea', '🇰🇷'),
       (13, 'SGD', 'Singapore', '🇸🇬'),
       (14, 'NOK', 'Norway', '🇳🇴'),
       (15, 'INR', 'India', '🇮🇳'),
       (16, 'MXN', 'Mexico', '🇲🇽'),
       (17, 'RUB', 'Russia', '🇷🇺'),
       (18, 'ZAR', 'South Africa', '🇿🇦'),
       (19, 'BRL', 'Brazil', '🇧🇷'),
       (20, 'TRY', 'Turkey', '🇹🇷'),
       (21, 'IDR(100)', 'Indonesia', '🇮🇩');

