CREATE TABLE exchange_rates (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RESULT INT NOT NULL COMMENT '1 : 성공, 2 : DATA코드 오류, 3 : 인증코드 오류, 4 : 일일제한횟수 마감',
    CUR_UNIT VARCHAR(10) NOT NULL COMMENT '통화코드',
    CUR_NM VARCHAR(100) COMMENT '국가/통화명',
    TTB VARCHAR(20) COMMENT '전신환(송금) 받으실때',
    TTS VARCHAR(20) COMMENT '전신환(송금) 보내실때',
    DEAL_BAS_R VARCHAR(20) COMMENT '매매 기준율',
    BKPR VARCHAR(20) COMMENT '장부가격',
    YY_EFEE_R VARCHAR(20) COMMENT '년환가료율',
    TEN_DD_EFEE_R VARCHAR(20) COMMENT '10일환가료율',
    KFTC_DEAL_BAS_R VARCHAR(20) COMMENT '서울외국환중계매매기준율',
    KFTC_BKPR VARCHAR(20) COMMENT '서울외국환중계장부가격',
    SEARCH_DATE VARCHAR(8) NOT NULL COMMENT '조회일자',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_SEARCH_DATE (SEARCH_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;